// Generated by tools/legal-approval-record.mjs --write. Do not edit by hand.
//
// The identifier a recorded acceptance points at. A clickwrap agreement is
// enforceable only if it can be shown who accepted which version, so this is
// derived from the pinned digests of the public notices themselves: edit any
// one of them, re-pin the approval record, and the version changes.

export const TERMS_VERSION = 'e4bbfaab7146872b';

/** The documents that version covers, and the digest each was pinned at. */
export const LEGAL_DOCUMENTS = Object.freeze([
  Object.freeze({ file: 'site/legal/aup.html', digest: '7926cbfdce4940ff' }),
  Object.freeze({ file: 'site/legal/biometric.html', digest: 'abc2001dfb7b6a4a' }),
  Object.freeze({ file: 'site/legal/copyright.html', digest: 'a102075c4a9b3b18' }),
  Object.freeze({ file: 'site/legal/eula.html', digest: 'a88712213e2f6990' }),
  Object.freeze({ file: 'site/legal/index.html', digest: '20c76c8d4f17e941' }),
  Object.freeze({ file: 'site/legal/licenses.html', digest: '85b26113d88e2b40' }),
  Object.freeze({ file: 'site/legal/privacy.html', digest: '948be30f3a4ebf88' }),
  Object.freeze({ file: 'site/legal/refunds.html', digest: 'c359f478235f23e3' }),
  Object.freeze({ file: 'site/legal/security.html', digest: '6cb2725c6ea11280' }),
  Object.freeze({ file: 'site/legal/terms.html', digest: '8d70901efcb2e559' }),
  Object.freeze({ file: 'site/legal/trademark.html', digest: '5eee881b99d919fd' }),
]);
