// WAV encoding for anything this product hands a customer, with the origin of
// the audio written into the file.
//
// Two reasons the marking is not optional.
//
// The law: from 2 August 2026, providers of AI systems that generate synthetic
// audio must mark the output in a machine-readable format and make it
// detectable as artificially generated (EU AI Act Article 50(2)). Systems
// already on the market before that date have until 2 December 2026. A bare
// 44-byte WAV header carries nothing, which is what this product wrote until
// now.
//
// Our own words: the Acceptable Use policy already tells customers that
// "provenance fields travel with exports". That was true of the photo side,
// which reads provenance on import, and untrue of every voice export.
//
// The marking is a RIFF LIST/INFO chunk, which is the standard place for it in
// a WAV and is read by ffprobe, mediainfo and ordinary audio tooling. The
// comment carries the IPTC digital source type vocabulary term for media made
// by a trained model, which is the same term C2PA carries and the same one
// js/analyze.js already looks for on import - so the product can read its own
// output and agree with itself.
//
// A signed C2PA manifest is the stronger form and needs a signing certificate,
// which is an owner decision, not a code one. This is the part that can be done
// without one, and it is detectable today.

/** The IPTC digital source type for media produced by a trained model. */
export const TRAINED_ALGORITHMIC_MEDIA = 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia';

/** What a listener or a tool is told about where the audio came from. */
export const SYNTHETIC_AUDIO_NOTE =
  'Synthetic speech generated by a trained model. digitalSourceType: ' + TRAINED_ALGORITHMIC_MEDIA;

const ascii = (view, offset, text) => {
  for (let i = 0; i < text.length; i++) view.setUint8(offset + i, text.charCodeAt(i) & 0x7f);
};

/**
 * One RIFF INFO field. Every chunk is padded to an even length, which the
 * format requires and naive writers forget; an odd-length field shifts every
 * later chunk by a byte and the file stops decoding.
 */
function infoField(id, value) {
  const text = String(value).replace(/[^\x20-\x7e]/g, ' ');
  const body = text.length + 1;               // NUL-terminated
  const padded = body + (body % 2);
  const bytes = new Uint8Array(8 + padded);
  const view = new DataView(bytes.buffer);
  ascii(view, 0, id);
  view.setUint32(4, body, true);
  ascii(view, 8, text);
  return bytes;
}

/**
 * The provenance block: what made this file, when, and what kind of thing it
 * is. `software` names the product and version; `note` says how it was made.
 */
export function provenanceChunk({ software, note = SYNTHETIC_AUDIO_NOTE, created = new Date() } = {}) {
  const fields = [
    infoField('ISFT', software),
    infoField('ICMT', note),
    infoField('ICRD', created.toISOString().slice(0, 10)),
    infoField('IGNR', 'Speech')
  ];
  const payload = fields.reduce((total, field) => total + field.length, 0);
  const chunk = new Uint8Array(12 + payload);
  const view = new DataView(chunk.buffer);
  ascii(view, 0, 'LIST');
  view.setUint32(4, 4 + payload, true);
  ascii(view, 8, 'INFO');
  let at = 12;
  for (const field of fields) { chunk.set(field, at); at += field.length; }
  return chunk;
}

/**
 * A 16-bit PCM WAV carrying its own provenance. Channels are interleaved in
 * the order given. Pass `provenance: null` only for a file that is not a
 * customer-facing output, and say why at the call site.
 */
export function encodeWav(channels, sampleRate, { provenance = {} } = {}) {
  const count = Math.max(1, channels.length);
  const frames = channels[0]?.length || 0;
  const info = provenance ? provenanceChunk(provenance) : null;
  const dataBytes = frames * count * 2;
  const total = 12 + 24 + (info ? info.length : 0) + 8 + dataBytes;
  const buffer = new ArrayBuffer(total);
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);

  ascii(view, 0, 'RIFF');
  view.setUint32(4, total - 8, true);
  ascii(view, 8, 'WAVE');

  ascii(view, 12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);                       // PCM
  view.setUint16(22, count, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * count * 2, true);  // byte rate
  view.setUint16(32, count * 2, true);               // block align
  view.setUint16(34, 16, true);

  // The provenance sits between fmt and data, where a reader meets it before
  // the audio and any chunk scanner finds it.
  let at = 36;
  if (info) { bytes.set(info, at); at += info.length; }

  ascii(view, at, 'data');
  view.setUint32(at + 4, dataBytes, true);
  at += 8;
  for (let frame = 0; frame < frames; frame++) {
    for (let channel = 0; channel < count; channel++) {
      const sample = channels[channel][frame] || 0;
      view.setInt16(at, Math.max(-1, Math.min(1, sample)) * 32767, true);
      at += 2;
    }
  }
  return buffer;
}

/** The same, straight from an AudioBuffer. */
export function encodeAudioBuffer(audioBuffer, options) {
  const channels = [];
  for (let index = 0; index < audioBuffer.numberOfChannels; index++) {
    channels.push(audioBuffer.getChannelData(index));
  }
  return encodeWav(channels, audioBuffer.sampleRate, options);
}

/** What a file declares about its own origin, read back from a WAV. */
export function readProvenanceChunk(buffer) {
  const view = new DataView(buffer);
  const text = new TextDecoder('latin1').decode(new Uint8Array(buffer));
  if (text.slice(0, 4) !== 'RIFF' || text.slice(8, 12) !== 'WAVE') return null;
  let at = 12;
  const found = {};
  while (at + 8 <= buffer.byteLength) {
    const id = text.slice(at, at + 4);
    const size = view.getUint32(at + 4, true);
    if (id === 'LIST' && text.slice(at + 8, at + 12) === 'INFO') {
      let field = at + 12;
      const end = Math.min(buffer.byteLength, at + 8 + size);
      while (field + 8 <= end) {
        const key = text.slice(field, field + 4);
        const length = view.getUint32(field + 4, true);
        found[key] = text.slice(field + 8, field + 8 + length).replace(/\0+$/, '');
        field += 8 + length + (length % 2);
      }
    }
    at += 8 + size + (size % 2);
  }
  if (!Object.keys(found).length) return null;
  return {
    software: found.ISFT || null,
    note: found.ICMT || null,
    created: found.ICRD || null,
    syntheticDeclared: (found.ICMT || '').includes('trainedAlgorithmicMedia')
  };
}
